/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as KolmarketsRouteImport } from './routes/kolmarkets'
import { Route as HowitworksRouteImport } from './routes/howitworks'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CryptomarketsRouteImport } from './routes/cryptomarkets'
import { Route as ClosedMarketsRouteImport } from './routes/closed-markets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketMarketIdRouteImport } from './routes/market.$marketId'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KolmarketsRoute = KolmarketsRouteImport.update({
  id: '/kolmarkets',
  path: '/kolmarkets',
  getParentRoute: () => rootRouteImport,
} as any)
const HowitworksRoute = HowitworksRouteImport.update({
  id: '/howitworks',
  path: '/howitworks',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptomarketsRoute = CryptomarketsRouteImport.update({
  id: '/cryptomarkets',
  path: '/cryptomarkets',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosedMarketsRoute = ClosedMarketsRouteImport.update({
  id: '/closed-markets',
  path: '/closed-markets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketMarketIdRoute = MarketMarketIdRouteImport.update({
  id: '/market/$marketId',
  path: '/market/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closed-markets': typeof ClosedMarketsRoute
  '/cryptomarkets': typeof CryptomarketsRoute
  '/docs': typeof DocsRoute
  '/howitworks': typeof HowitworksRoute
  '/kolmarkets': typeof KolmarketsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$marketId': typeof MarketMarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closed-markets': typeof ClosedMarketsRoute
  '/cryptomarkets': typeof CryptomarketsRoute
  '/docs': typeof DocsRoute
  '/howitworks': typeof HowitworksRoute
  '/kolmarkets': typeof KolmarketsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$marketId': typeof MarketMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closed-markets': typeof ClosedMarketsRoute
  '/cryptomarkets': typeof CryptomarketsRoute
  '/docs': typeof DocsRoute
  '/howitworks': typeof HowitworksRoute
  '/kolmarkets': typeof KolmarketsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$marketId': typeof MarketMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/closed-markets'
    | '/cryptomarkets'
    | '/docs'
    | '/howitworks'
    | '/kolmarkets'
    | '/leaderboard'
    | '/portfolio'
    | '/market/$marketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/closed-markets'
    | '/cryptomarkets'
    | '/docs'
    | '/howitworks'
    | '/kolmarkets'
    | '/leaderboard'
    | '/portfolio'
    | '/market/$marketId'
  id:
    | '__root__'
    | '/'
    | '/closed-markets'
    | '/cryptomarkets'
    | '/docs'
    | '/howitworks'
    | '/kolmarkets'
    | '/leaderboard'
    | '/portfolio'
    | '/market/$marketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosedMarketsRoute: typeof ClosedMarketsRoute
  CryptomarketsRoute: typeof CryptomarketsRoute
  DocsRoute: typeof DocsRoute
  HowitworksRoute: typeof HowitworksRoute
  KolmarketsRoute: typeof KolmarketsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PortfolioRoute: typeof PortfolioRoute
  MarketMarketIdRoute: typeof MarketMarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolmarkets': {
      id: '/kolmarkets'
      path: '/kolmarkets'
      fullPath: '/kolmarkets'
      preLoaderRoute: typeof KolmarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howitworks': {
      id: '/howitworks'
      path: '/howitworks'
      fullPath: '/howitworks'
      preLoaderRoute: typeof HowitworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cryptomarkets': {
      id: '/cryptomarkets'
      path: '/cryptomarkets'
      fullPath: '/cryptomarkets'
      preLoaderRoute: typeof CryptomarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closed-markets': {
      id: '/closed-markets'
      path: '/closed-markets'
      fullPath: '/closed-markets'
      preLoaderRoute: typeof ClosedMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$marketId': {
      id: '/market/$marketId'
      path: '/market/$marketId'
      fullPath: '/market/$marketId'
      preLoaderRoute: typeof MarketMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosedMarketsRoute: ClosedMarketsRoute,
  CryptomarketsRoute: CryptomarketsRoute,
  DocsRoute: DocsRoute,
  HowitworksRoute: HowitworksRoute,
  KolmarketsRoute: KolmarketsRoute,
  LeaderboardRoute: LeaderboardRoute,
  PortfolioRoute: PortfolioRoute,
  MarketMarketIdRoute: MarketMarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
